# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46983b1b01fab37415cd962953d848ac08945d7f61f9552d70fc93bfbd5cf31f820081facec042371136996cbd9989ca48e7c179a37ca9c7f65f9ba432724fcf

test:
  secret_key_base: cb08dcd2147d4fecba1e2d927f554b5a14e96cbb061ae5db47b2eed9099a7d65d250a124d25314d63f6dc07518e5e2ed5217dac1695c6582fd91d0a678070b8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
